version: '3.8'

services:
  app:
    build: .
    container_name: pdf-vectorizer
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: text-embedding-3-small
      EMBEDDING_DIM: 1536
      QDRANT_COLLECTION: pdf_documents
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - pdf-vectorizer-net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - pdf-vectorizer-net

networks:
  pdf-vectorizer-net:
    driver: bridge

volumes:
  qdrant_storage: