version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: pdf-vectorizer
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: text-embedding-3-small
      EMBEDDING_DIM: 1536
      QDRANT_COLLECTION: pdf_documents
    ports:
      - "1382:1382"
    depends_on:
      - qdrant